project:
  type: website

website:

  search:
    location: sidebar
    type: overlay
  navbar:
    background: "#0A4393"
    height: 55
    foreground: "light"
    logo: "_images/logos/combinedLogo.svg"
    pinned: true
    
  page-navigation: true
    
    
  title: "COPERNICUS DATA SPACE ECOSYSTEM DOCUMENTATION PORTAL"
  

  sidebar:
    style: "floating"
    collapse-level: 1
    contents:
      - href: Home.md
        text: Welcome
      # - section: "Service description and evolution roadmap"
      #   href: Roadmap.md
      #   contents: 
      #     - href: Roadmap/DataTable.qmd
      #     - href: Roadmap/APITable.qmd
      #     - href: Roadmap/AppTable.qmd
      # - href: Registration.md
      #   text: User registration and authentication
      # - section: "Data"
      #   href: Data.md
      #   contents: 
      #     - href: Data/Sentinel1.md
      #     - href: Data/Sentinel2.md
      #     - href: Data/Sentinel3.md
      #     - href: Data/Sentinel5P.md
      # - section: "APIs"
      #   href: APIs.md
      #   contents: 
      #     - href: APIs/OData.md
      #     - href: APIs/OpenSearch.md
      # - section: "Applications"
      #   href: Applications.md
      #   contents: 
      #     - href: Applications/Browser.md
      # - href: FAQ.md
      #   text: FAQ
      # - href: Support.md
      #   text: Support
      - section: "Data Offering"
        contents: 
        - section: "Copernicus & Sentinel data"
          href: Data.md
          contents: 
          - Data/Sentinel1.md 
          - Data/Sentinel2.md 
          - Data/Sentinel3.md 
          - Data/Sentinel5P.md 
        - section: "On-demand & Commercial data"
        - section: "Copernicus Contributing Mission"
        - section: "Federated datasets"
        - text: "---"
      - section: "Tools"
        href: Applications.md
        contents: 
        - Applications/Browser.md
        - section: "Marketplace"
        - section: "Jupyter Hub"
        - section: "Data workspace and on-demand processing"
        - section: "OpenEO web editor"
        - section: "Dashboard"
        - section: "Traceability service"
        - text: "---"
      - section: "APIs"
        contents: 
        - section: "Catalogue and download APIs"
          href: APIs.md
          contents:
          - APIs/OData.md
          - APIs/OpenSearch.md 
          - section: "STAC"
          - section: "S3"
        - section: "OpenEO Hub"
        - section: "Sentinel Hub"
          contents:
          - section: "Synchronous"
          - section: "Statistical"
          - section: "Async"
          - section: "Batch"
          - section: "BYOD"
        - section: "Traceability"
        - section: "On-demand production"
        - text: "---"
      - section: "Ecosystem services"
        contents: 
        - section: "Commercial services"
        - section: "Public services"
        - text: "---"
    


format:
  html:
    toc: true
    toc-depth: 3
    css: custom.scss
